server:
  port: 8052
spring:
  application:
    name: feign
  profiles:
    active: client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8050/eureka/
